# -*- coding: utf-8 -*-
"""CSE420_LAB02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTEQW1IrCKGEx1SISnb-ctTJdJFLyiAz
"""

myfile = open("/content/a.txt", "r") 
lines = myfile.readlines()
lines.pop(0)
i=0
statementForEmail = "Email : "
statementForWeb = "Website : "
while i < len(lines): 
    lines[i] =  lines[i].replace('\n','')
    if (not lines[i].startswith('.') and not lines[i].endswith('.') and '@' in lines[i]  and not '..' in lines[i]):
        stateForEmail = 0
        charArr = list(lines[i])
        for j in charArr:
            if(stateForEmail==0 and j.isalnum()) :
                stateForEmail = 1
            elif(stateForEmail==1 and j.isalnum()) : 
                stateForEmail = 1
            elif(stateForEmail==1 and j=='.') :
                stateForEmail = 4
            elif(stateForEmail==1 and j=='@') :
                stateForEmail = 2
            elif(stateForEmail==2 and j.isalnum()) :
                stateForEmail = 3
            elif(stateForEmail==3 and j.isalnum()) :
                stateForEmail = 3
            elif(stateForEmail==3 and j=='.') :
                stateForEmail = 5
            elif(stateForEmail==4 and j.isalnum()) :
                stateForEmail = 1
            elif(stateForEmail==5 and j.isalnum()) :
                stateForEmail = 6
            elif(stateForEmail==6 and j.isalnum()) :
                stateForEmail = 6
            elif(stateForEmail==6 and j=='.') :
                stateForEmail = 6
        if(stateForEmail==6) :
            statementForEmail = statementForEmail+str(i+1)+" "
    if (lines[i].startswith("www.") and not lines[i].endswith('.') and not '..' in lines[i]):
        stateForWeb = 0
        charArr2 = list(lines[i])
        for j in charArr2:
            if(stateForWeb==0 and j.isalnum()):
                stateForWeb = 0
            elif(stateForWeb==0 and j=='.'):
                stateForWeb = 1
            elif(stateForWeb==1 and j.isalnum()):
                stateForWeb = 2
            elif(stateForWeb==2 and j.isalnum()):
                stateForWeb = 2
            elif(stateForWeb==2 and j=='.'):
                stateForWeb = 3
            elif(stateForWeb==3 and j.isalnum()):
                stateForWeb = 4
            elif(stateForWeb==4 and j.isalnum()):
                stateForWeb = 4
            elif(stateForWeb==4 and j=='.'):
                stateForWeb = 3
        if(stateForWeb==4) :
            statementForWeb = statementForWeb+str(i+1)+" "
    i += 1
print(statementForEmail)
print(statementForWeb)