# -*- coding: utf-8 -*-
"""18101708CSE420LAB04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OyEChK8ngWAlCeDjPooq4b5mAo3rHM-l
"""

myfile = open("/content/sample_data/a.txt", "r") 
lines = myfile.readlines()
methods_list = []
name_list = []
i = 0
while i < len(lines): 
    lines[i] =  lines[i].replace('\n','')
    if (lines[i].startswith("public") and lines[i].__contains__('(') ) :
      if  lines[i].count("main") == 0:
        methods_list.append(lines[i])
    i+=1
method_length = len(methods_list)

for i in range(0,method_length):
    name_list = methods_list[i].split('(')
    name_list[0] = name_list[0].replace('public ','')
    name_list[0] = name_list[0].replace('static ','')
    
    if(name_list[0].__contains__('int') or name_list[0].__contains__('void') or name_list[0].__contains__('double') ):
        return_type = name_list[0].split(' ')
        
    else :
        return_type[0] = ''
    name_list[0] = name_list[0].replace('void ','')
    name_list[0] = name_list[0].replace('int ','')
    name_list[0] = name_list[0].replace('double ','')
    
    
    print(name_list[0]+" ("+name_list[1] +", return type : "+return_type[0])